name: jot
description: An experimental documentation generator for Dart projects.
version: 0.1.0-dev
repository: https://github.com/devoncarew/jot

environment:
  sdk: ^2.19.0

dependencies:
  analyzer: ^5.7.1
  args: ^2.4.0
  cli_util: ^0.4.0
  collection: ^1.17.0
  dart_style: ^2.2.0
  js: ^0.6.0
  markdown: ^7.0.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.0
