name: package:jot
permissions: read-all

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable, beta, dev]
        include:
          - sdk: stable
            run-tests: true
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3
        with:
          sdk: ${{matrix.sdk}}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{matrix.run-tests}}

      # Ensure that the front-end is up to date.
      - run: dart tool/build_web.dart --verify

      # Ensure that we can build the front-end.
      - run: dart tool/build_web.dart

      - run: dart test
        if: ${{matrix.run-tests}}

      # Ensure that we can build the Dart SDK docs.
      - run: dart tool/create_dart_sdk.dart
