name: package:jot
permissions: read-all

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [beta, dev] # todo: add back in stable
        include:
          - sdk: beta
            run-tests: true
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: ${{matrix.sdk}}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{matrix.run-tests}}

      - run: dart compile js -o lib/resources/script.js -O2 web/main.dart
        if: ${{matrix.run-tests}}

      - run: dart test
        if: ${{matrix.run-tests}}
